# Generated by Django 5.2.6 on 2025-11-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField()),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('current', 'Current'), ('past', 'Past')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exhibitions/')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_carousel/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Homepage Carousel Image',
                'verbose_name_plural': 'Homepage Carousel Images',
            },
        ),
        migrations.CreateModel(
            name='InfoPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='info/')),
                ('bio', models.TextField(help_text='Finn-Mac’s bio or artist statement')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Info Page Content',
                'verbose_name_plural': 'Info Page Content',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('link', models.URLField(blank=True, help_text='Optional external link (e.g. Bandcamp, Vimeo)', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('composer', 'Composer'), ('post_production_audio', 'Post-Production Audio'), ('sound_design', 'Sound Design'), ('sound_recordist', 'Sound Recordist')], max_length=100, unique=True)),
                ('title', models.CharField(help_text='Display title for the service', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short one-line summary displayed under the title', max_length=255)),
                ('description', models.TextField(help_text='Main description for the top section of the service page')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('areas_of_work', models.TextField(blank=True, help_text='One bullet point per line for the list of areas/services')),
                ('process', models.TextField(blank=True, help_text='Optional section describing methods, workflow, or approach')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
