# Generated by Django 5.2.6 on 2025-09-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField()),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('current', 'Current'), ('past', 'Past')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exhibitions/')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_carousel/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Homepage Carousel Image',
                'verbose_name_plural': 'Homepage Carousel Images',
            },
        ),
        migrations.CreateModel(
            name='InfoPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='info/')),
                ('bio', models.TextField(help_text='Finn-Mac’s bio or artist statement')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Info Page Content',
                'verbose_name_plural': 'Info Page Content',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sumup_link', models.URLField(help_text='Paste the SumUp payment link here')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PageImage',
        ),
    ]
