# Generated by Django 5.2.6 on 2025-11-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_service_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='areas_of_work',
            field=models.TextField(blank=True, help_text='One bullet point per line for the list of areas/services'),
        ),
        migrations.AddField(
            model_name='service',
            name='process',
            field=models.TextField(blank=True, help_text='Optional section describing methods, workflow, or approach'),
        ),
        migrations.AddField(
            model_name='service',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short one-line summary displayed under the title', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Main description for the top section of the service page'),
        ),
    ]
